- id: terraform_fmt
  name: Terraform fmt
  description: Rewrites all Terraform configuration files to a canonical format.
  entry: terraform_fmt.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: terraform_docs
  name: Terraform docs
  description: Inserts input and output documentation into README.md (using terraform-docs).
  entry: terraform_docs.sh
  args: [--args=--with-aggregate-type-defaults]
  language: script
  files: (\.tf)$
  exclude: \.terraform\/.*$

- id: terraform_docs_without_aggregate_type_defaults
  name: Terraform docs (without aggregate type defaults)
  description: Inserts input and output documentation into README.md (using terraform-docs).
  entry: terraform_docs.sh
  language: script
  files: (\.tf)$
  exclude: \.terraform\/.*$

- id: terraform_docs_replace
  name: Terraform docs (overwrite README.md)
  language: python
  entry: terraform_docs_replace
  files: (\.tf)$
  exclude: \.terraform\/.*$
  description: Overwrite content of README.md with terraform-docs

- id: terraform_validate_no_variables
  name: Terraform validate without variables
  description: Validates all Terraform configuration files without checking whether all required variables were set (basic check).
  entry: terraform_validate_no_variables.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: terraform_validate_with_variables
  name: Terraform validate with variables
  description: Validates all Terraform configuration files and checks whether all required variables were specified.
  entry: terraform_validate_with_variables.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$
